#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Lxappearance state=floating center=true
bspc rule -a mpv state=floating center=true

# autostart programs
compton --vsync opengl-swc --backend glx &
tint2 &
nm-applet &
volumeicon &
cbatticon &
~/.fehbg &
